title: "Abdelrahman Mohamed — Engineering Portfolio"
email: "abdelrahman11246@gmail.com"
description: "A collection of engineering and aerospace projects."
baseurl: "/abdelrahman-portfolio"
url: "https://naqeeb1124.github.io" # Replace with your GitHub Pages URL

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: "_projects"
    values:
      layout: default
  - scope:
      path: "_projects/13-child-development-program-website/child-development-website/node_modules"
    values:
      published: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins (if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files and folders from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Include specific files or folders
include:
  - _projects


# GitHub Pages settings
github:
  is_project_page: true